"""Tests for the griffe → MDX API reference generator."""
import importlib.util
import sys
from pathlib import Path

import pytest

SCRIPT_PATH = Path(__file__).resolve().parents[1] / "build_api_reference.py"


def _load_module():
    spec = importlib.util.spec_from_file_location("build_api_reference", SCRIPT_PATH)
    assert spec and spec.loader, f"cannot load {SCRIPT_PATH}"
    mod = importlib.util.module_from_spec(spec)
    sys.modules["build_api_reference"] = mod
    spec.loader.exec_module(mod)
    return mod


def test_render_signature_includes_return_annotation():
    mod = _load_module()
    rendered = mod.render_signature(
        name="run",
        parameters=[("self", None, None), ("x", "int", None)],
        returns="str",
    )
    assert "run(self, x: int) -> str" in rendered


def test_render_docstring_parses_google_sections():
    mod = _load_module()
    doc = (
        "Summary line.\n\n"
        "Args:\n"
        "    name (str): The name.\n\n"
        "Returns:\n"
        "    bool: Whether it worked.\n"
    )
    out = mod.render_docstring(doc)
    assert "Summary line." in out
    assert "**Args**" in out
    assert "`name`" in out
    assert "**Returns**" in out


def test_emit_module_writes_generated_marker(tmp_path):
    mod = _load_module()
    module_path = tmp_path / "cubepi-utils.mdx"
    mod.emit_module(
        out_path=module_path,
        module_name="cubepi.utils",
        sidebar_position=6,
        symbols=[],
        commit_sha="abc1234",
    )
    body = module_path.read_text(encoding="utf-8")
    assert body.startswith("---\n")
    assert "title: cubepi.utils" in body
    assert "<!-- GENERATED by build-api-reference.py — DO NOT EDIT -->" in body
